### ISSUE TITLE
CustomerID Sample Not Working Correctly

### ISSUE THREAD

**Issue by joseajimenezjr** [adobe/target-nodejs-sdk-samples#7]
Hello, currently having an issue with the sample that leverages customer ID sample. I keep getting a 400 response when using the out of the box client and orgid info plus the default customer id and integration code or when I use my own. What I have noticed is that when using the customer ID sample, I don't seem to get a full mbox cookie value and when I use one of the other samples I do. When debugging the code, Target responds with a 200 code but the body is actually a 400. Attached are screenshots of what I am seeing.
<img width="1297" alt="Screen Shot 2019-10-28 at 11 23 34 AM" src="https://user-images.githubusercontent.com/44737675/67693872-cea7b580-f978-11e9-853e-906481eb1e7c.png">

**Comment by XDex** [comment]
@joseajimenezjr This looks like an issue in the server-side ECID library, there's some missing functionality in what regards MCMID generation in case of new visitors, when no AMCV cookie is received from the client-side on first call. I'll open an internal issue with the ECID team and hopefully it will get fixed in an upcoming `visitor-js-server` release..
Until it's fixed, as a temporary workaround, [thirdPartyId](https://developers.adobetarget.com/api/delivery-api/#section/Identifying-Visitors/Third-Party-ID) should be set in the Delivery request, and no errors will be returned..

**Comment by joseajimenezjr** [comment]
Still getting a 400 error with this work around suggested. 
<img width="463" alt="Screen Shot 2019-11-04 at 11 54 11 AM" src="https://user-images.githubusercontent.com/44737675/68140543-fc9d7480-fef9-11e9-9e5b-94b1a5f412f1.png">

**Comment by XDex** [comment]
@joseajimenezjr Please include the `thirdPartyId` in the `id` section of the Delivery API request: https://developers.adobetarget.com/api/delivery-api/#section/Identifying-Visitors/Third-Party-ID

**Comment by XDex** [comment]
@joseajimenezjr Also, note the issue only occurs for first-time visitors, once content is returned to the client-side and the client-side Visitor.js library is initialized, all subsequent server-side Target calls will contain the proper MCMID sent via AMCV cookie from the client-side..

**Comment by XDex** [comment]
@joseajimenezjr Unfortunately it is currently no possible to generate the MCMID on the server-side, due to dependencies on AAM and cross-domain targeting, which can only be satisfied on the client-side. So, for the time being, ECID integration for first-time visitors (when no AMCV cookie is being sent in the first request to the server-side app) is broken. We will soon be updating the docs to reflect this..

**Comment by joseajimenezjr** [comment]
Was this ever resolved?

**Comment by lu83** [comment]
We are also looking for a straightforward way to generate a visitor id fully server-side.
